---
 
- name: Install spacewalk api script
  copy: 
    src: "{{ role_path }}/files/swapi.py"
    dest: /usr/sbin/swapi.py
    owner: root 
    group: root 
    mode: 0755

- name: Install spacewalk api config
  template: 
    src: swapi.conf.j2
    dest: /etc/swapi.conf
    owner: root 
    group: root 
    mode: 0644

- name: Install regen-apt-repodata.py script
  copy: 
    src: "{{ role_path }}/files/regen-apt-repodata.py"
    dest: /usr/sbin/regen-apt-repodata.py
    owner: root 
    group: root 
    mode: 0755

- name: Install reposync script
  template: 
    src: RepoSync.sh.j2
    dest: /usr/sbin/RepoSync.sh
    owner: root 
    group: root 
    mode: 0755

- include: gpg.yml

- name: Add reposync cronjob file under /etc/cron.d/
  cron:
    name: reposync
    weekday: "*"
    minute: "02"
    hour: "19"
    user: root
    job: "/usr/sbin/RepoSync.sh"
    cron_file: ansible_reposync
